name: Go Build Check

on:
  # 监听合并到 master 的两种方式：
  push:
    branches: [ "main" ] # 直接推送到 master 时触发
  pull_request:
    types: [ opened, synchronize ] # 监听 PR 创建和更新事件
    branches: [ "main" ] # 仅针对目标分支是 master 的 PR

jobs:
  build:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          $(go env GOMODCACHE)
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Build
      run: go build -v ./...
    # - name: Run Tests
    #   run: go test -v ./...
